"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const battle_class_1 = require("./class/battle.class");
const pokemon_class_1 = require("./class/pokemon.class");
const type_enum_1 = require("./class/type.enum");
const p1 = new pokemon_class_1.Pokemon("P1", type_enum_1.Type.Dragon, 10, 100);
const p2 = new pokemon_class_1.Pokemon("P2", type_enum_1.Type.Ice, 7, 50);
console.log(p1.name);
const b1 = new battle_class_1.Battle(p1, p2);
b1.first();
