"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Type;
(function (Type) {
    Type[Type["Normal"] = 0] = "Normal";
    Type[Type["Fire"] = 1] = "Fire";
    Type[Type["Water"] = 2] = "Water";
    Type[Type["Grass"] = 3] = "Grass";
    Type[Type["Electric"] = 4] = "Electric";
    Type[Type["Ice"] = 5] = "Ice";
    Type[Type["Fighting"] = 6] = "Fighting";
    Type[Type["Poison"] = 7] = "Poison";
    Type[Type["Ground"] = 8] = "Ground";
    Type[Type["Flying"] = 9] = "Flying";
    Type[Type["Psychic"] = 10] = "Psychic";
    Type[Type["Bug"] = 11] = "Bug";
    Type[Type["Rock"] = 12] = "Rock";
    Type[Type["Ghost"] = 13] = "Ghost";
    Type[Type["Dark"] = 14] = "Dark";
    Type[Type["Dragon"] = 15] = "Dragon";
    Type[Type["Steel"] = 16] = "Steel";
    Type[Type["Fairy"] = 17] = "Fairy";
})(Type = exports.Type || (exports.Type = {}));
